[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
registry = "occakrum1PrVDaXauDuSiwPKfrhdnm7uVWKJxE39kfm"

[programs.devnet]
registry = "occakrum1PrVDaXauDuSiwPKfrhdnm7uVWKJxE39kfm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/registry"]

[scripts]
# No JS-based tests yet; we'll add bankrun/integration tests in CP3.
test = "echo 'no tests yet'"
